/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'say';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String MESSENGER = 'assets/images/Messenger.png';
  static const String NOTIFICATION = 'assets/images/Notification.png';
  static const String PLUS = 'assets/images/Plus.png';
  static const String PROFILE = 'assets/images/Profile.png';
  static const String SEARCH = 'assets/images/Search.png';
  static const String STORE = 'assets/images/Store.png';
  static const String FACEBOOK_ICON = 'assets/images/facebook_icon.svg';
  static const String HOME = 'assets/images/home.png';
  static const String IMAGEPLUSE = 'assets/images/imagePluse.png';
  static const String ISMAILY = 'assets/images/ismaily.png';
  static const String META_LOGO = 'assets/images/meta_logo.svg';
  static const String RONALDO = 'assets/images/ronaldo.png';
  static const String UYD = 'assets/images/uyd.png';
  static const String VID = 'assets/images/vid.png';
}
